// Auto-generated by mixcontext --init
// Learn more: https://github.com/mixcontext

import type { BuildOpts } from 'mixcontext-core';

const config: BuildOpts = {
  /** Include a folder with raw input files inside the bundle */
  zipOriginals: true,

  /** Configure vector embeddings */
  embed: {
    provider: 'openai',
    apiKey: process.env.OPENAI_KEY!,
    model: 'text-embedding-3-small'
  },

  /** Enable OCR when parsing images or scanned PDFs */
  ocr: false,

  /** Enable aggressive duplicate-chunk removal */
  dedupe: true
};

export default config;
