name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: Node ${{ matrix.node-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests (with coverage)
        run: pnpm test -- --run --coverage

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.node-version }}
          path: |
            coverage/**/*.json

      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          # Pick up all JSON coverage reports (Vitest v8 provider)
          files: ./coverage/**/*.json
          flags: node-${{ matrix.node-version }}
          token: ''
          fail_ci_if_error: false
